[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "imbalanced-learn>=0.13.0",
    "imblearn>=0.0",
    "matplotlib>=3.10.3",
    "numpy>=2.2.5",
    "pandas>=2.2.3",
    "plotly>=6.1.0",
    "scikit-learn>=1.6.1",
    "streamlit>=1.45.1",
    "tensorflow>=2.14.0",
    "xgboost>=3.0.1",
    "xlsxwriter>=3.2.3",
]
